"""Chapter 26 — Regression: Predicting House Prices."""
from gen import *

PART = "V"


def build():
    return page(
        chapter_open(
            "regression",
            "The first complete project: predict a house's sale price from nine numbers describing it. It uses every "
            "piece of Parts I–III in the order a real project needs them: load a CSV, split, scale, build a model, "
            "train with validation and early stopping, report errors in dollars, save the model with its scalers, and "
            "serve predictions from a separate inference mode. The code is the repository's "
            "<code>NeuralSharp.Samples.HousePrices</code> project; this chapter walks through it and shows how to "
            "adapt it to any numeric prediction task.",
            "Task type: <b>regression</b> (predict a number). Loss MSE, metric MAE, report MAE/RMSE/MAPE/R² in real units.",
            "Data: <code>houses.csv</code>, 2,500 rows, 9 numeric features and a <code>price</code> column.",
            "Model: 9 → 64 → 32 → 1 MLP with ReLU and light dropout (2,753 parameters).",
            "Result on the CPU: MAE $15,570 (5.3%), R² 0.975, in under a second of training.",
            "Three files make the model: weights, feature scaler, price scaler.",
        ),
        h2("26.1 The project at a glance"),
        reftable(["Step", "API", "Chapter"], [
            ["Load CSV", "<code>Dataset.LoadCsv(path, new CsvOptions { TargetColumns = [\"price\"], IgnoreColumns = [\"id\"] })</code>", ch("data", None)],
            ["Split", "<code>houses.Split(0.8, seed: 1)</code>", ch("data", None)],
            ["Scale", "<code>StandardScaler.FitFeatures(train)</code>, <code>FitTargets(train)</code>, <code>Scale</code>", ch("data", None)],
            ["Model", "<code>Sequential</code> of <code>Linear</code>, <code>ReLU</code>, <code>Dropout</code>", ch("dense", None)],
            ["Train", "<code>Trainer</code> with <code>Adam</code>, MSE, MAE metric, early stopping", ch("trainer", None)],
            ["Evaluate", "<code>trainer.Predict</code>, <code>InverseTransform</code>, <code>RegressionReport</code>", ch("metrics", None)],
            ["Save / serve", "<code>model.Save</code>, <code>scaler.Save</code>; <code>--predict</code> mode loads them", ch("modules", None) + ", " + ch("inference", None)],
        ], caption="Table 26.1 — The pipeline and where each part is explained"),
        deriv("Creating the project yourself", [
            "<code>dotnet new console -n HousePrices</code>, then <code>cd HousePrices</code>.",
            "<code>dotnet add reference ../NN/src/NeuralSharp/NeuralSharp.csproj</code>.",
            "Copy your CSV to <code>data/houses.csv</code> and mark it to copy to the output folder "
            "(<code>&lt;None Update=\"data\\**\" CopyToOutputDirectory=\"PreserveNewest\" /&gt;</code> in the .csproj).",
            "Write <code>Program.cs</code> as in the sections below; run with <code>dotnet run -c Release</code>.",
            "Or run the finished sample: <code>dotnet run -c Release --project samples/NeuralSharp.Samples.HousePrices -- --cpu</code> (or <code>--cuda</code>).",
        ]),
        h2("26.2 The data"),
        output("""
            id,area_sqft,bedrooms,bathrooms,age_years,distance_km,quality,garage_spaces,has_pool,lot_sqft,price
            1,2291,5,3,4,35.7,8,1,0,11952,313600
            2,2073,4,3,48,2.8,5,0,0,3328,420300
            """, caption="The first lines of houses.csv (generated by the sample if missing)"),
        snippet("""
            var houses = Dataset.LoadCsv(dataPath, new CsvOptions
            {
                TargetColumns = ["price"],
                IgnoreColumns = ["id"],
            });
            var (train, test) = houses.Split(trainFraction: 0.8, seed: 1);

            // Fit on the training set only, so nothing about the test set leaks into training.
            var featureScaler = StandardScaler.FitFeatures(train);
            var priceScaler = StandardScaler.FitTargets(train);
            var trainScaled = train.Scale(featureScaler, priceScaler);
            var testScaled = test.Scale(featureScaler, priceScaler);

            var trainLoader = new DataLoader(trainScaled, batchSize: 64, shuffle: true, device: device, seed: 1);
            var testLoader = new DataLoader(testScaled, batchSize: 512, device: device);
            """, caption="Loading, splitting and scaling"),
        h2("26.3 The model and training"),
        snippet("""
            // One factory for training AND inference, so saved weights always fit.
            Sequential BuildModel(int features, Random? random = null)
            {
                var model = new Sequential
                {
                    new Linear(features, 64, device: device, random: random), new ReLU(), new Dropout(0.05f, random),
                    new Linear(64, 32, device: device, random: random), new ReLU(),
                    new Linear(32, 1, device: device, random: random),        // plain Linear: any price
                };
                model.Name = "house-price-mlp";
                return model;
            }

            using var model = BuildModel(houses.FeatureCount, new Random(1));
            using var optimizer = new Adam(model.Parameters(), learningRate: 0.002f);
            var trainer = new Trainer(model, optimizer, Losses.MeanSquaredError)
            {
                Metrics = { Metric.MeanAbsoluteError },
                EarlyStoppingPatience = 30,
            };
            var history = trainer.Fit(trainLoader, epochs: 400, validation: testLoader);
            """, caption="Model factory and Trainer"),
        output("""
            Loaded Dataset(2,500 samples, features [area_sqft, bedrooms, bathrooms, age_years, distance_km, quality, garage_spaces, has_pool, lot_sqft] -> targets [price]) in 49 ms
            Split: 2000 training / 500 test samples

            Training on cpu (CPU (4 threads, 8-wide SIMD)) | 2,000 samples, 500 validation | batch 64, 32 steps/epoch | Adam lr=0.002 | 2,753 parameters | 4 CPU threads
            Epoch   1/400  loss 0.314442  mae 0.3958  val_loss 0.100076  val_mae 0.2459  60.5 ms  33,053 samples/s  *
            Epoch  10/400  loss 0.036492  mae 0.1423  val_loss 0.026273  val_mae 0.1227  12.3 ms  162,621 samples/s  *
            Epoch  20/400  loss 0.030439  mae 0.1295  val_loss 0.023986  val_mae 0.1134  16.4 ms  122,096 samples/s
            Epoch  30/400  loss 0.028837  mae 0.1260  val_loss 0.025198  val_mae 0.1153  18.9 ms  105,895 samples/s
            Epoch  40/400  loss 0.024654  mae 0.1203  val_loss 0.024709  val_mae 0.1185  12.6 ms  158,650 samples/s
            Epoch  50/400  loss 0.024179  mae 0.1159  val_loss 0.025291  val_mae 0.1158  6.0 ms  331,614 samples/s
            Epoch  60/400  loss 0.022677  mae 0.1126  val_loss 0.026736  val_mae 0.1201  8.6 ms  232,758 samples/s
            Finished 63 epochs in 0.88 s (early stop) | best epoch 33 loss 0.023277
            Best epoch: 33 (validation loss 0.02328), stopped early and restored its weights
            """, caption="Training output (CPU)"),
        h2("26.4 Errors in dollars"),
        snippet("""
            var scaledPredictions = trainer.Predict(testScaled);
            float[] predicted = [.. scaledPredictions.Cast<float>()];
            priceScaler.InverseTransform(predicted, 1);                      // back to dollars
            var report = RegressionReport.Compute(predicted, test.Targets);   // test.Targets: unscaled prices
            """, caption="Unscale, then score"),
        output("""
            Test set:
              Mean absolute error:     $15,570
              Root mean squared error: $21,387
              Mean absolute % error:   5.3 %
              R²:                      0.9750

               area  beds baths  age  dist qual |     actual |  predicted |  error
            -----------------------------------+------------+------------+-------
               1875     3     2   38  36.6    6 |   $214,600 |   $221,552 |  3.2 %
               1907     3     2   40   6.4    5 |   $414,900 |   $355,627 | -14.3 %
               1623     3     2    5  23.0    9 |   $256,600 |   $274,063 |  6.8 %
               2096     3     3   61  12.7    4 |   $279,600 |   $289,097 |  3.4 %
               1239     2     2   57   2.2    5 |   $276,300 |   $259,323 | -6.1 %
                908     2     1   19  13.0    6 |   $175,200 |   $177,453 |  1.3 %
                450     1     1   68   1.5    5 |   $112,100 |   $138,612 | 23.7 %
               1728     3     2   68  16.2   10 |   $291,800 |   $312,154 |  7.0 %
            """, caption="Evaluation output"),
        h2("26.5 Saving and serving"),
        snippet("""
            model.Save(modelPath);                            // house-price.weights
            featureScaler.Save(featureScalerPath);            // house-price.features.txt
            priceScaler.Save(priceScalerPath);                // house-price.price.txt

            // --- inference mode (a separate run, or a separate program) ---
            using var served = BuildModel(FeatureCount);
            served.Load(modelPath);
            var fx = StandardScaler.Load(featureScalerPath);
            var fy = StandardScaler.Load(priceScalerPath);

            float[] features = [2100, 4, 2, 15, 9.5f, 7, 2, 0, 6500,   1200, 3, 1, 30, 12, 5, 1, 0, 4000];
            fx.Transform(features, FeatureCount);
            using var input = Tensor.From(features, [2, FeatureCount], device);
            using var output = served.Predict(input);
            float[] prices = output.ToArray();
            fy.InverseTransform(prices, 1);
            """, caption="Save three files; load them to predict"),
        cpugpu("training and serving from the command line",
               """
               dotnet run -c Release --project samples/NeuralSharp.Samples.HousePrices -- --cpu
               dotnet run -c Release --project samples/NeuralSharp.Samples.HousePrices -- --cpu --predict --input "2100,4,2,15,9.5,7,2,0,6500;1200,3,1,30,12,5,1,0,4000"
               """,
               """
               dotnet run -c Release --project samples/NeuralSharp.Samples.HousePrices -- --cuda
               dotnet run -c Release --project samples/NeuralSharp.Samples.HousePrices -- --cuda --predict --data new-listings.csv
               """,
               "A model trained on either device is served on either device; <code>--data file.csv</code> prices every row "
               "and, if the file has a price column, reports the error."),
        output("""
            Loaded .../models/house-price.weights

              2100,4,2,15,9.5,7,2,0,6500             $390,612
              1200,3,1,30,12,5,1,0,4000              $192,873
            """, caption="--predict output"),
        h2("26.6 Adapting it to your data"),
        reftable(["Your situation", "Change"], [
            ["Different columns", "Only <code>TargetColumns</code>/<code>IgnoreColumns</code>; the model reads <code>FeatureCount</code>"],
            ["Several numbers to predict (price and rent)", "<code>TargetColumns = [\"price\", \"rent\"]</code>, last layer <code>Linear(32, 2)</code>"],
            ["Targets from 10 to 10,000,000", "Train on log(target), predict exp(output); or MAE loss"],
            ["Outliers in the targets", "<code>Losses.MeanAbsoluteError</code> or the Huber loss of " + ch("losses")],
            ["Text or category columns", "Map them to ids and use embeddings (" + ch("recommender") + ")"],
            ["Fewer than a few hundred rows", "Smaller model (16 units), more dropout/weight decay, k-fold validation (" + ch("data") + ")"],
            ["Hundreds of thousands of rows", "Wider model (128–256), batch 256+, consider the GPU"],
        ], caption="Table 26.2 — Common adaptations"),
        trap("serving without the scalers",
             "<p>The model was trained on standardized inputs and predicts standardized prices. Feeding raw square feet "
             "and reading the raw output gives numbers near zero. Always load and apply both scalers.</p>"),
        practice([
            (1, "Which three files must a web service load to price houses, and in which order are they used?",
             "The feature scaler (applied to the input), the weights (the model), and the price scaler (applied to the output)."),
            (1, "The MAE is $15,570 but the RMSE $21,387. What does the gap tell you?",
             "Errors vary: a few larger misses (like the −14% and +24% rows) raise RMSE more than MAE."),
            (2, "Predict both price and yearly property tax from the same features.",
             "Add the tax column to <code>TargetColumns</code>, set the last layer to <code>Linear(32, 2)</code>, and fit the target "
             "scaler on both columns; <code>RegressionReport</code> can then be computed per column on the unscaled outputs."),
            (2, "Make the model train on the GPU but serve on a CPU-only server.",
             "Run training with <code>--cuda</code>; copy the three files to the server and run <code>--predict --cpu</code> (or build "
             "the model with <code>device: Device.Cpu</code>). Weight files are device-independent."),
            (3, "Replace MSE on prices with MSE on log-prices and compare MAPE.",
             "Transform targets with <code>MathF.Log</code> before fitting the price scaler, and apply <code>MathF.Exp</code> after "
             "<code>InverseTransform</code>. Log-targets make the loss relative, which usually lowers MAPE on cheap houses."),
        ], PART),
        footer("Regression", "Feature", "Target", "MAE", "RMSE", "R²", "StandardScaler", "Early stopping", "Inference mode"),
    )
