<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>NeuralSharp.Samples.HouseApi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NeuralSharp\NeuralSharp.csproj" />
    <ProjectReference Include="..\..\src\NeuralSharp.AspNetCore\NeuralSharp.AspNetCore.csproj" />
  </ItemGroup>

</Project>
