<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Shared\*.cs" LinkBase="Shared" />
    <Compile Include="..\Shared\Gpt\*.cs" LinkBase="Shared\Gpt" />
    <ProjectReference Include="..\..\src\NeuralSharp\NeuralSharp.csproj" />
  </ItemGroup>

</Project>
