<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Shared\*.cs" LinkBase="Shared" />
    <Compile Include="..\NeuralSharp.Samples.ReRanker\Collection.cs" Link="Collection.cs" />
    <ProjectReference Include="..\..\src\NeuralSharp\NeuralSharp.csproj" />
  </ItemGroup>

</Project>
